// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieTableEdit.Data;

#nullable disable

namespace MovieTableEdit.Migrations
{
    [DbContext(typeof(MovieTableEditContext))]
    [Migration("20240913083133_VersionDataTypeAdjustment")]
    partial class VersionDataTypeAdjustment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MovieTableEdit.Models.MockAnimePriceDE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RatingDE")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MockAnimePriceDE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 2.51m,
                            ProductId = 20000,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 2,
                            Price = 2.78m,
                            ProductId = 20001,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 3,
                            Price = 3.55m,
                            ProductId = 20002,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 4,
                            Price = 8.43m,
                            ProductId = 20003,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 5,
                            Price = 13.49m,
                            ProductId = 20004,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 6,
                            Price = 2.51m,
                            ProductId = 20000,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 7,
                            Price = 2.78m,
                            ProductId = 20001,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 8,
                            Price = 3.55m,
                            ProductId = 20002,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 9,
                            Price = 8.43m,
                            ProductId = 20003,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 10,
                            Price = 13.49m,
                            ProductId = 20004,
                            RatingDE = 1,
                            Version = 1.01m
                        });
                });

            modelBuilder.Entity("MovieTableEdit.Models.MockAnimePriceFR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RatingFR")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MockAnimePriceFR", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 2.51m,
                            ProductId = 20000,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 2,
                            Price = 2.78m,
                            ProductId = 20001,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 3,
                            Price = 3.55m,
                            ProductId = 20002,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 4,
                            Price = 8.43m,
                            ProductId = 20003,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 5,
                            Price = 13.49m,
                            ProductId = 20004,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 6,
                            Price = 2.51m,
                            ProductId = 20000,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 7,
                            Price = 2.78m,
                            ProductId = 20001,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 8,
                            Price = 3.55m,
                            ProductId = 20002,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 9,
                            Price = 8.43m,
                            ProductId = 20003,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 10,
                            Price = 13.49m,
                            ProductId = 20004,
                            RatingFR = 1,
                            Version = 1.01m
                        });
                });

            modelBuilder.Entity("MovieTableEdit.Models.MockComicPriceDE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RatingDE")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MockComicPriceDE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 2.51m,
                            ProductId = 30000,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 2,
                            Price = 2.78m,
                            ProductId = 30001,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 3,
                            Price = 3.55m,
                            ProductId = 30002,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 4,
                            Price = 8.43m,
                            ProductId = 30003,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 5,
                            Price = 13.49m,
                            ProductId = 30004,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 6,
                            Price = 2.51m,
                            ProductId = 30000,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 7,
                            Price = 2.78m,
                            ProductId = 30001,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 8,
                            Price = 3.55m,
                            ProductId = 30002,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 9,
                            Price = 8.43m,
                            ProductId = 30003,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 10,
                            Price = 13.49m,
                            ProductId = 30004,
                            RatingDE = 1,
                            Version = 1.01m
                        });
                });

            modelBuilder.Entity("MovieTableEdit.Models.MockComicPriceFR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RatingFR")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MockComicPriceFR", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 2.51m,
                            ProductId = 30000,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 2,
                            Price = 2.78m,
                            ProductId = 30001,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 3,
                            Price = 3.55m,
                            ProductId = 30002,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 4,
                            Price = 8.43m,
                            ProductId = 30003,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 5,
                            Price = 13.49m,
                            ProductId = 30004,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 6,
                            Price = 2.51m,
                            ProductId = 30000,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 7,
                            Price = 2.78m,
                            ProductId = 30001,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 8,
                            Price = 3.55m,
                            ProductId = 30002,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 9,
                            Price = 8.43m,
                            ProductId = 30003,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 10,
                            Price = 13.49m,
                            ProductId = 30004,
                            RatingFR = 1,
                            Version = 1.01m
                        });
                });

            modelBuilder.Entity("MovieTableEdit.Models.MockGenreDim", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GenreId");

                    b.ToTable("MockGenreDim", (string)null);

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            Genre = "SciFi"
                        },
                        new
                        {
                            GenreId = 2,
                            Genre = "Action"
                        },
                        new
                        {
                            GenreId = 3,
                            Genre = "Esoteric"
                        },
                        new
                        {
                            GenreId = 4,
                            Genre = "Drama"
                        },
                        new
                        {
                            GenreId = 5,
                            Genre = "Fantasy"
                        },
                        new
                        {
                            GenreId = 6,
                            Genre = "Musical"
                        },
                        new
                        {
                            GenreId = 7,
                            Genre = "Comedy"
                        },
                        new
                        {
                            GenreId = 8,
                            Genre = "History/biography"
                        });
                });

            modelBuilder.Entity("MovieTableEdit.Models.MockMoviePriceDE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RatingDE")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MockMoviePriceDE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 2.51m,
                            ProductId = 1111,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 2,
                            Price = 2.78m,
                            ProductId = 1112,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 3,
                            Price = 3.55m,
                            ProductId = 1113,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 4,
                            Price = 8.43m,
                            ProductId = 1114,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 5,
                            Price = 13.49m,
                            ProductId = 1115,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 6,
                            Price = 2.51m,
                            ProductId = 1111,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 7,
                            Price = 2.78m,
                            ProductId = 1112,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 8,
                            Price = 3.55m,
                            ProductId = 1113,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 9,
                            Price = 8.43m,
                            ProductId = 1114,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 10,
                            Price = 13.49m,
                            ProductId = 1115,
                            RatingDE = 1,
                            Version = 1.01m
                        });
                });

            modelBuilder.Entity("MovieTableEdit.Models.MockMoviePriceFR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RatingFR")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MockMoviePriceFR", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 2.51m,
                            ProductId = 1111,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 2,
                            Price = 2.78m,
                            ProductId = 1112,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 3,
                            Price = 3.55m,
                            ProductId = 1113,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 4,
                            Price = 8.43m,
                            ProductId = 1114,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 5,
                            Price = 13.49m,
                            ProductId = 1115,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 6,
                            Price = 2.51m,
                            ProductId = 1111,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 7,
                            Price = 2.78m,
                            ProductId = 1112,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 8,
                            Price = 3.55m,
                            ProductId = 1113,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 9,
                            Price = 8.43m,
                            ProductId = 1114,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 10,
                            Price = 13.49m,
                            ProductId = 1115,
                            RatingFR = 1,
                            Version = 1.01m
                        });
                });

            modelBuilder.Entity("MovieTableEdit.Models.MockProductDim", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleDE")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleES")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleFR")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleIT")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleJP")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("MockProductDim", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1111,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "Red River",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 1112,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "The Last Picture Show",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 1113,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "Network",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 1114,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "Traffic",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 1115,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "Florida Project",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 2222,
                            GenreId = 3,
                            ProductTypeId = 1,
                            Title = "The Marriage of Maria Braun",
                            TitleDE = "Die Ehe der Maria Braun",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 2223,
                            GenreId = 3,
                            ProductTypeId = 1,
                            Title = "Aguirre the Wrath of God",
                            TitleDE = "Aguirre der Zorn Gottes",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 2224,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "Head-On",
                            TitleDE = "Gegen die Wand",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 3333,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "Children of Paradise",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "Les Enfants du Paradis",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 3334,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "The Wages of Fear",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "Le Salaire de la peur",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 3335,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "Portrait of a Lady on Fire",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "Portrait de la jeune fille en feu",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 4444,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "Talk to Her",
                            TitleDE = "",
                            TitleES = "Hable Con Ella",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 4445,
                            GenreId = 3,
                            ProductTypeId = 1,
                            Title = "The Spirit of the Beehive",
                            TitleDE = "",
                            TitleES = "El espíritu de la colmena",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 4446,
                            GenreId = 5,
                            ProductTypeId = 1,
                            Title = "Pan's Labyrinth",
                            TitleDE = "",
                            TitleES = "El Laberinto Del Fauno",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 5555,
                            GenreId = 6,
                            ProductTypeId = 1,
                            Title = "The Red Shoes",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 5556,
                            GenreId = 7,
                            ProductTypeId = 1,
                            Title = "Hot Fuzz",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 6666,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "Nights of Cabiria",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "Le notti di Cabiria",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 6667,
                            GenreId = 3,
                            ProductTypeId = 1,
                            Title = "The Conformist",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "Il conformista",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 6668,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "Gomorrah",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "Gomorra",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 6669,
                            GenreId = 8,
                            ProductTypeId = 1,
                            Title = "Il Divo",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "Il Divo",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 7777,
                            GenreId = 2,
                            ProductTypeId = 1,
                            Title = "Seven Samurai",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "七人の侍"
                        },
                        new
                        {
                            ProductId = 7778,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "Sansho the Bailiff",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "山椒大夫"
                        },
                        new
                        {
                            ProductId = 7779,
                            GenreId = 3,
                            ProductTypeId = 1,
                            Title = "Woman in the Dunes",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "砂の女"
                        },
                        new
                        {
                            ProductId = 7780,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "Harakiri",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "切腹"
                        },
                        new
                        {
                            ProductId = 7781,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "Merry Christmas, Mr. Lawrence ",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "戦場のメリークリスマス"
                        },
                        new
                        {
                            ProductId = 7782,
                            GenreId = 4,
                            ProductTypeId = 1,
                            Title = "In This Corner of the World",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "この世界の片隅に"
                        },
                        new
                        {
                            ProductId = 10000,
                            GenreId = 7,
                            ProductTypeId = 2,
                            Title = "Monty Python’s Flying Circus",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 10001,
                            GenreId = 7,
                            ProductTypeId = 2,
                            Title = "M*A*S*H",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 10002,
                            GenreId = 4,
                            ProductTypeId = 2,
                            Title = "The Sopranos",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 10003,
                            GenreId = 4,
                            ProductTypeId = 2,
                            Title = "Mad Men",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 10004,
                            GenreId = 4,
                            ProductTypeId = 2,
                            Title = "Fanny and Alexander",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 10005,
                            GenreId = 4,
                            ProductTypeId = 2,
                            Title = "Dekalog",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 20000,
                            GenreId = 2,
                            ProductTypeId = 3,
                            Title = "Attack on Titan",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "進撃の巨人"
                        },
                        new
                        {
                            ProductId = 20001,
                            GenreId = 2,
                            ProductTypeId = 3,
                            Title = "JoJo's Bizarre Adventure Stardust Crusaders\r\n",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "ジョジョの奇妙な冒険 スターダストクルセイダース"
                        },
                        new
                        {
                            ProductId = 20002,
                            GenreId = 2,
                            ProductTypeId = 3,
                            Title = "JoJo's Bizarre Adventure Diamond Is Unbreakable\r\n",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "ジョジョの奇妙な冒険 ダイヤモンドは砕けない"
                        },
                        new
                        {
                            ProductId = 20003,
                            GenreId = 2,
                            ProductTypeId = 3,
                            Title = "JoJo's Bizarre Adventure Golden Wind\r\n",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "ジョジョの奇妙な冒険 黄金の風"
                        },
                        new
                        {
                            ProductId = 20004,
                            GenreId = 2,
                            ProductTypeId = 3,
                            Title = "JoJo's Bizarre Adventure Stone Ocean\r\n",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "ジョジョの奇妙な冒険 ストーンオーシャン"
                        },
                        new
                        {
                            ProductId = 30000,
                            GenreId = 8,
                            ProductTypeId = 4,
                            Title = "Kingdom",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "キングダム"
                        },
                        new
                        {
                            ProductId = 30001,
                            GenreId = 4,
                            ProductTypeId = 4,
                            Title = "Orb: On the Movements of the Earth",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "チ。地球の運動について"
                        },
                        new
                        {
                            ProductId = 30002,
                            GenreId = 4,
                            ProductTypeId = 4,
                            Title = "Blood on Tracks",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "血の轍"
                        },
                        new
                        {
                            ProductId = 30003,
                            GenreId = 5,
                            ProductTypeId = 4,
                            Title = "Berserk",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = "ベルセルク"
                        },
                        new
                        {
                            ProductId = 30004,
                            GenreId = 8,
                            ProductTypeId = 4,
                            Title = "Persepolis",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        },
                        new
                        {
                            ProductId = 30005,
                            GenreId = 4,
                            ProductTypeId = 4,
                            Title = "Watchmen",
                            TitleDE = "",
                            TitleES = "",
                            TitleFR = "",
                            TitleIT = "",
                            TitleJP = ""
                        });
                });

            modelBuilder.Entity("MovieTableEdit.Models.MockProductTypeDim", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProductTypeId");

                    b.ToTable("MockProductTypeDim", (string)null);

                    b.HasData(
                        new
                        {
                            ProductTypeId = 1,
                            ProductType = "Movie"
                        },
                        new
                        {
                            ProductTypeId = 2,
                            ProductType = "TV Show"
                        },
                        new
                        {
                            ProductTypeId = 3,
                            ProductType = "Animated Series"
                        },
                        new
                        {
                            ProductTypeId = 4,
                            ProductType = "Comic"
                        });
                });

            modelBuilder.Entity("MovieTableEdit.Models.MockRatingDEDim", b =>
                {
                    b.Property<int>("RatingDEId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RatingDE")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RatingDEId");

                    b.ToTable("MockRatingDEDim", (string)null);

                    b.HasData(
                        new
                        {
                            RatingDEId = 1,
                            RatingDE = "German-G"
                        },
                        new
                        {
                            RatingDEId = 2,
                            RatingDE = "German-PG"
                        },
                        new
                        {
                            RatingDEId = 3,
                            RatingDE = "German-PG-13"
                        },
                        new
                        {
                            RatingDEId = 4,
                            RatingDE = "German-R"
                        },
                        new
                        {
                            RatingDEId = 5,
                            RatingDE = "German-NC-17"
                        });
                });

            modelBuilder.Entity("MovieTableEdit.Models.MockRatingFRDim", b =>
                {
                    b.Property<int>("RatingFRId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RatingFR")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RatingFRId");

                    b.ToTable("MockRatingFRDim", (string)null);

                    b.HasData(
                        new
                        {
                            RatingFRId = 1,
                            RatingFR = "French-G"
                        },
                        new
                        {
                            RatingFRId = 2,
                            RatingFR = "French-PG"
                        },
                        new
                        {
                            RatingFRId = 3,
                            RatingFR = "French-PG-13"
                        },
                        new
                        {
                            RatingFRId = 4,
                            RatingFR = "French-R"
                        },
                        new
                        {
                            RatingFRId = 5,
                            RatingFR = "French-NC-17"
                        });
                });

            modelBuilder.Entity("MovieTableEdit.Models.MockTVPriceDE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RatingDE")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MockTVPriceDE", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 2.51m,
                            ProductId = 10001,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 2,
                            Price = 2.78m,
                            ProductId = 10002,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 3,
                            Price = 3.55m,
                            ProductId = 10003,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 4,
                            Price = 8.43m,
                            ProductId = 10004,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 5,
                            Price = 13.49m,
                            ProductId = 10005,
                            RatingDE = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 6,
                            Price = 2.51m,
                            ProductId = 10001,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 7,
                            Price = 2.78m,
                            ProductId = 10002,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 8,
                            Price = 3.55m,
                            ProductId = 10003,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 9,
                            Price = 8.43m,
                            ProductId = 10004,
                            RatingDE = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 10,
                            Price = 13.49m,
                            ProductId = 10005,
                            RatingDE = 1,
                            Version = 1.01m
                        });
                });

            modelBuilder.Entity("MovieTableEdit.Models.MockTVPriceFR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RatingFR")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MockTVPriceFR", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 2.51m,
                            ProductId = 10001,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 2,
                            Price = 2.78m,
                            ProductId = 10002,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 3,
                            Price = 3.55m,
                            ProductId = 10003,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 4,
                            Price = 8.43m,
                            ProductId = 10004,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 5,
                            Price = 13.49m,
                            ProductId = 10005,
                            RatingFR = 1,
                            Version = 1.00m
                        },
                        new
                        {
                            Id = 6,
                            Price = 2.51m,
                            ProductId = 10001,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 7,
                            Price = 2.78m,
                            ProductId = 10002,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 8,
                            Price = 3.55m,
                            ProductId = 10003,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 9,
                            Price = 8.43m,
                            ProductId = 10004,
                            RatingFR = 1,
                            Version = 1.01m
                        },
                        new
                        {
                            Id = 10,
                            Price = 13.49m,
                            ProductId = 10005,
                            RatingFR = 1,
                            Version = 1.01m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
